default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: bookstore-backend_development
  username: postgres
  password: '123'
  host: localhost

test:
  <<: *development
  database: bookstore-backend_test

production:
  database: d98doh241bnpjo
  username: azjphsngwpqkxe
  password: 930f0e2b556c9383c1afba79a37cd26371c13d24acac90084e0cde23269f772e
  url: postgres://azjphsngwpqkxe:930f0e2b556c9383c1afba79a37cd26371c13d24acac90084e0cde23269f772e@ec2-23-23-247-245.compute-1.amazonaws.com:5432/d98doh241bnpjo